Add Relayout / Restyle, and bug fix ExtendTraces
LayTec-AG/Plotly.Blazor pull request #50
Opened 2020-10-14 13:54 UTC by Peop1eCanF1y

ExtendTraces was buggy if there was more than 1 Trace in the chart, I fixed it.
I add the Relayout command.
I add the Restyle command, Restyle can be used like this:
                        ScatterGl updateScatterChart = new ScatterGl();
                        updateScatterChart.YAxis = "y2";
                        await plotlyChart.Restyle(updateScatterChart, 0);
the change is applied back to the ITrace object with (line 197 in file PlotlyChart.razor)
Newtonsoft.Json.JsonConvert.PopulateObject(json, currentTrace); // apply change to the existing object

2020-10-19 07:27 UTC, sean-mcleish reviewed
Hi,

thanks for your contribution!
I have noted one thing regarding the dependency on the Newtonsoft library. Have a nice start into the week!

2020-10-19 07:27 UTC, sean-mcleish commented on Plotly.Blazor/Plotly.Blazor.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
Is there an alternative for using this library? We have intended to remain independent from Newtonsoft.

2020-10-19 07:27 UTC, sean-mcleish commented on Plotly.Blazor/PlotlyChart.razor
> +            Newtonsoft.Json.JsonConvert.PopulateObject(json, currentTrace); // apply change to the existing object
Maybe an alternative? https://stackoverflow.com/questions/56835040/net-core-3-0-jsonserializer-populate-existing-object/56906228

2020-10-19 12:49 UTC, sean-mcleish requested changes
Waiting for an alternative solution regarding Newtonsoft.


Edit: Will edit it afterwards

2020-10-22 12:57 UTC, merged

2020-10-22 13:01 UTC, sean-mcleish commented
Fixes #18 #19

2020-10-27 10:01 UTC, Peop1eCanF1y commented
Thanks for the rework, I saw the merge. I will be more careful next time.